#url of rss feed
url = ""
#download path
path = ""

#if false run check once and exit, if true keep checking RSS feed indefinitely
run_forever = "false"

#interval to check RSS feed in minutes
check_timer = 15

#show or surpress error messages
verbose = "true"

#number of simultaneous downloads
parallel_download = 4

#regex patern to include
match = ""

#regex patern to exclude
match_false = ""
