#url of rss feed
url = ""

#download path
path = ""

#show or surpress error messages
verbose = "false"

#number of simultaneous downloads
parallel_download = 4

#regex patern to include
match = ""

#regex patern to exclude
match_false = ""
